apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: caddy-private
  namespace: caddy-test
spec:
  ingressClassName: caddy-private
  rules:
    - host: caddy.vms.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caddy
                port:
                  number: 80