replicaCount: 2

nameOverride: caddy-public

loadBalancer:
  enabled: false

service:
  type: LoadBalancer
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  annotations:
    metallb.io/address-pool: public-v6-pool
    metallb.io/allow-shared-ip: caddy-public
  ipDualStack:
    enabled: true
    ipFamilies:
      - IPv6
      - IPv4
    ipFamilyPolicy: PreferDualStack

ingressController:
  className: caddy-public
  classNameRequired: true
  leaseId: caddy-public
  config:
    metrics: true
    debug: false
    # Set a real email before installing so Caddy can manage ACME certificates.
    email: admin@example.com