replicaCount: 2

nameOverride: caddy-private

loadBalancer:
  enabled: false

service:
  type: LoadBalancer
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  annotations:
    metallb.io/address-pool: private-v6-pool
  ipDualStack:
    enabled: true
    ipFamilies:
      - IPv6
    ipFamilyPolicy: SingleStack

ingressController:
  className: caddy-private
  classNameRequired: true
  leaseId: caddy-private
  config:
    metrics: true
    debug: false
    email: "kube@cloudstrife.vms.lan"
    acmeCA: https://cloudstrife.vms.lan/acme/acme/directory
    acmeCARoot: /etc/caddy/acme-root.pem

extraEnv:
  - name: CADDY_INGRESS_CONTROLLER_ACME_CA_ROOT
    value: /etc/caddy/acme-root.pem

extraVolumes:
  - name: acme-root
    secret:
      secretName: internal-acme-root

extraVolumeMounts:
  - name: acme-root
    mountPath: /etc/caddy
    readOnly: true