# Private pool — VMS network (ens18), ULA IPv6 only
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: private-v6-pool
  namespace: metallb-system
spec:
  addresses:
    - fd38:82fc:4248:44:1::100-fd38:82fc:4248:44:1::150
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: private-v6
  namespace: metallb-system
spec:
  ipAddressPools:
    - private-v6-pool
  interfaces:
    - ens18
---
# Public pool — DMZ network (ens19), GUA IPv6 + IPv4 NAT
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public-pool
  namespace: metallb-system
spec:
  addresses:
    - 2001:470:e309:88:1::100-2001:470:e309:88:1::150
    - 172.16.88.100-172.16.88.150
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: public
  namespace: metallb-system
spec:
  ipAddressPools:
    - public-pool
  interfaces:
    - ens19